baseURL: "https://ryanfaiz.netlify.app/"
title: Ryan Faiz
paginate: 5
theme: PaperModX

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

enableInlineShortcodes: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
  category: categories
  tag: tags


params:
  env: production
  title: Ryan Faiz
  description: "Ryan Faiz Sanie - Tech News Article Tutorial"
  keywords: [Article, Blog, News, Tech, Tutorial]
  author: Ryan Faiz Sanie
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light, or auto
  disableThemeToggle: false

  EnableInstantClick: true
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  favicon: /favicon.ico
  appleTouchIcon: /icons/apple-touch-icon.webp
  logo:
    icon: /icons/favicon.webp

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/saniefaiz"
    - name: github
      url: "https://github.com/ryanfaiz"
    - name: buymeacoffee
      url: "https://saweria.co/ryanfaiz"
    - name: rss
      url: "/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
menu:
    main:
        - name: Archives
          url: archives/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true